### ISSUE TITLE
Does this model only work for websites?

### ISSUE THREAD

**Issue by andupotorac** [JulianGuerreiro/LayoutFlow#1]
From the demo it is not clear if this model could be used to generate smaller components also - think a quiz, a poll, a video player, etc - where it would be able to randomize multiple UIs if requested.

**Comment by JulianGuerreiro** [comment]
Hi, thank you for your question! 

I'm not quite sure if I understand your question correctly, but our proposed model strongly depends on its training dataset. Specifically, we separately trained it on the two publicly available datasets RICO (based on UI layouts) and PubLayNet (based on the layout of academic papers). If you want to apply it to your own type of data, it would be necessary to re-train the model with your own data, so it can learn the corresponding layout patterns. 

In terms of the components, there are in theory no restrictions, but you would likely need to adjust some hyperparameters, such as the number of categories.

**Comment by andupotorac** [comment]
> Hi, thank you for your question!
> 
> I'm not quite sure if I understand your question correctly, but our proposed model strongly depends on its training dataset. Specifically, we separately trained it on the two publicly available datasets RICO (based on UI layouts) and PubLayNet (based on the layout of academic papers). If you want to apply it to your own type of data, it would be necessary to re-train the model with your own data, so it can learn the corresponding layout patterns.
> 
> In terms of the components, there are in theory no restrictions, but you would likely need to adjust some hyperparameters, such as the number of categories.

What I meant is if this model can be used for example to generate the UI of an audio player, and it would look different for each generation. I believe having trained it on UI layouts would have included widgets within those UIs too.

**Comment by andupotorac** [comment]
For example, I'm wondering if I can take an input like this from an LLM:
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/f9bc911b-860f-4e9f-a3f8-721c02187e73">

And then use a Type-conditioned Generation RICO, where I tell it the elements that should be part of that layout, and if the currently trained model can in fact take this and try to generate random layouts.

**Comment by andupotorac** [comment]
So then for example, with that info, it would be able to create layouts that are different, yet follow the given structure. Like these examples:



<img width="760" alt="Screenshot 2024-09-22 at 13 25 13" src="https://github.com/user-attachments/assets/34decbe1-05c6-4b3a-8bbc-6226cfd3568d">

<img width="651" alt="Screenshot 2024-09-22 at 13 26 17" src="https://github.com/user-attachments/assets/fc96a258-4058-4b14-ac68-113bd2a00b5e">

<img width="892" alt="Screenshot 2024-09-22 at 13 25 48" src="https://github.com/user-attachments/assets/6a074f9d-01ef-4734-93e3-527fb554f139">

**Comment by JulianGuerreiro** [comment]
I'm sorry, but I think that in your problem setting, the type-conditioned Generation based on the RICO dataset would not produce good results, because the RICO dataset did not include audio player layouts (as far as I'm aware). However, if you train LayoutFlow with a dataset consisting of audio players layouts, then it would be possible.

**Comment by andupotorac** [comment]
Thanks so much for the info, this helps and I know what the next steps could be! I'll close out the issue now.
